name: Build Android App for Multiple Clients

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Pad APK
        run: ./gradlew build

      - name: Upload Pad APK
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: app/build/outputs/apk/*.apk


 
